add keepassxc authentication to dotfiles script

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -43,8 +43,7 @@ set -e
 ##########################
 # Paths
 ##########################
-KPXC_VAULT="$HOME/SynologyDrive/Passwords.kdbx"
-
+ENV_FILE="$HOME/.dotfiles_env"
 DOTFILES_LOG="$HOME/.dotfiles.log"
 DOTFILES_DIR="$HOME/.dotfiles"
 SSH_DIR="$HOME/.ssh"
@@ -56,9 +55,11 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
 #########################
 # Variables
 #########################
+if [ -f "${ENV_FILE}" ]; then
+    set -a; source "${ENV_FILE}"; set +a;
+fi
 KPXC_INSTALLED=false
 KPXC_AUTHENTICATED=false
-KPXC_VAULT_SECRET=""
 ID=""
 
 # _header colorize the given argument with spacing
@@ -257,11 +258,15 @@ update_ansible_galaxy() {
 }
 
 function confirmVaultAccess() {
-  __task "Checking for keepassxc-cli"
+  __task "Checking for Keepassxc CLI"
   if keepassxc-cli --version >/dev/null 2>&1; then
     KPXC_INSTALLED=true
-    keepassxc-cli db-info $KPXC_VAULT
-    KPXC_AUTHENTICATED=true
+    if [[ -n "$KPXC_VAULT" ]] && [[ -n $KPXC_PW ]]; then
+	echo "${KPXC_PW}" | keepassxc-cli db-info -q "${KPXC_VAULT} > /dev/null"
+	if [ $? -eq 0 ]; then
+    	    KPXC_AUTHENTICATED=true
+	fi
+    fi
   fi
 }
 
@@ -318,15 +323,15 @@ update_ansible_galaxy $ID
 confirmVaultAccess
 
 
-#if [[ -n $OP_INSTALLED ]]; then
-#  if [[ -n $OP_AUTHENTICATED ]]; then
-#    printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}Checking for 1Password CLI: 1Password Authentication successful! ☕${NC}\n"
+if [[ -n $KPXC_INSTALLED ]]; then
+  if [[ -n $KPXC_AUTHENTICATED ]]; then
+    printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}Checking for Keepassxc CLI: Keepassxc Authentication successful! ☕${NC}\n"
 #    rm -f $VAULT_SECRET_FILE
     ansible-playbook "$DOTFILES_DIR/main.yml" "$@"
-#  else
-#    printf "${OVERWRITE}${LRED} [X]  ${LRED}Checking for 1Password CLI: Unable to Authenticate with 1Password.${NC}\n"
-#  fi
-#fi
+  else
+    printf "${OVERWRITE}${LRED} [X]  ${LRED}Checking for 1Password CLI: Unable to Authenticate with 1Password.${NC}\n"
+  fi
+fi
 
 popd 2>&1 > /dev/null
 
